import { AlignmentType, Document, HeadingLevel, Packer, Paragraph, Table, TableCell, TableRow, TextRun, WidthType, } from "docx";
function createCell(text, bold = false, width = 10) {
    return new TableCell({
        width: {
            size: width,
            type: WidthType.PERCENTAGE,
        },
        children: [
            new Paragraph({
                children: [
                    new TextRun({
                        text,
                        bold,
                        font: "Tahoma",
                        size: 18,
                    }),
                ],
            }),
        ],
    });
}
function createHeaderRow() {
    return new TableRow({
        tableHeader: true,
        children: [
            createCell("Sl. No", true, 5),
            createCell("Case No", true, 15),
            createCell("Case Name", true, 35),
            createCell("Stage", true, 10),
            createCell("Bench", true, 15),
            createCell("Court", true, 10),
            createCell("Item", true, 10),
        ],
    });
}
function createDataRows(data) {
    return data.causelist.map((el, i) => new TableRow({
        children: [
            createCell(String(i + 1), false, 5),
            createCell(el.caseNo || "", false, 15),
            createCell(el.parties || "", false, 35),
            createCell(el.list || "", false, 10),
            createCell(el.benchName || "", false, 15),
            createCell(el.courtHall || "", false, 10),
            createCell(`Item ${el.itemNo}\n ${el.items || ""}`, false, 10),
        ],
    }));
}
function createNoticeTable() {
    return new Table({
        width: {
            size: 100,
            type: WidthType.PERCENTAGE,
        },
        rows: [
            new TableRow({
                children: [
                    new TableCell({
                        children: [
                            new Paragraph({
                                alignment: AlignmentType.CENTER,
                                children: [
                                    new TextRun({
                                        text: "NOTICE",
                                        bold: true,
                                        font: "Tahoma",
                                    }),
                                ],
                            }),
                            new Paragraph({
                                text: "Stage information is currently unavailable due to changes in the High Court data source. Users are advised to verify Admission/Hearing status and other stage-related details from the official daily cause list PDF.",
                            }),
                            new Paragraph({
                                spacing: {
                                    after: 200,
                                },
                            }),
                            new Paragraph({
                                text: "Data is sourced from the official website of the High Court of Kerala, which retains copyright over the information.",
                            }),
                            new Paragraph({
                                alignment: AlignmentType.CENTER,
                                children: [
                                    new TextRun({
                                        text: "Cause List generated by DocketDesk",
                                        bold: true,
                                        font: "Tahoma",
                                    }),
                                ],
                            }),
                            new Paragraph({
                                alignment: AlignmentType.CENTER,
                                children: [
                                    new TextRun({
                                        text: "docketdesk.app",
                                        font: "Tahoma",
                                    }),
                                ],
                            }),
                        ],
                    }),
                ],
            }),
        ],
    });
}
export async function createWordDocument(data) {
    const table = new Table({
        width: {
            size: 100,
            type: WidthType.PERCENTAGE,
        },
        rows: [createHeaderRow(), ...createDataRows(data)],
    });
    const doc = new Document({
        sections: [
            {
                children: [
                    new Paragraph({
                        heading: HeadingLevel.HEADING_1,
                        alignment: AlignmentType.CENTER,
                        children: [
                            new TextRun({
                                text: "Causelist",
                                bold: true,
                                font: "Tahoma",
                                size: 24,
                            }),
                        ],
                    }),
                    new Paragraph({
                        spacing: {
                            after: 200,
                        },
                    }),
                    table,
                    new Paragraph({
                        spacing: {
                            after: 200,
                        },
                    }),
                    createNoticeTable(),
                ],
            },
        ],
    });
    return await Packer.toBuffer(doc);
}
